# Generated by Django 5.1 on 2024-08-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0002_rename_book_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
