# Generated by Django 5.1 on 2024-09-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
